// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActionFromClient(arg1:string,arg2:string):Promise<void>;

export function ConnectToServer(arg1:string,arg2:any):Promise<void>;
