// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActionFromClient(arg1, arg2) {
  return window['go']['main']['App']['ActionFromClient'](arg1, arg2);
}

export function ConnectToServer(arg1, arg2) {
  return window['go']['main']['App']['ConnectToServer'](arg1, arg2);
}
