package helpers

import (
	globalvariables "server/globalVariables"
)

//this function will check if the device is registered first from the frontend (i.e code is generated by the user),then we can connect with the device by entering the code in client app
func CheckIfDeviceRegistered(deviceID string) bool {
    _, exists := globalvariables.AddedDeviceMap[deviceID]
    return exists
}
